### PR TITLE
Enable CSS additions to all project pages

### PR DESCRIPTION
**Pull request by lsgs**
Enabling CSS additions to non survey and data entry form project pages.

Hello ctsit team. Thanks very much for this very handy module. I've been using it in production for a while now but there have been a couple of occasions where I wanted to do something on a project page that is not a data entry or survey form. I've made a few tweaks to support that functionality and thought I'd submit them to you so you can take a look and see whether you're interested in incorporating changes along these lines into your repo. No worries if not - my version is working for me! (Actually the branching logic on the form selection is not, but I'm suspecting a framework bug atm...)

### CODE REVIEW

**Comment by h3n0r1k** [comment]
hey, would love to use this version, is this gonna be released any time soon? @pbchase @marlycormar

**Comment by pbchase** [comment]
@h3n0r1k, I assigned the review to Kyle. The code, interface, and docs look sound, but I don't have time to test it. Kyle _might_, but we are working on a big contact tracing project right now. I'm about to move from design phase to coding phase so he will get busy very soon.

**Comment by h3n0r1k** [comment]
@pbchase Thanks for the update, hope @ChemiKyle has a few more minutes to spare :) Otherwise ill overwrite the code myself on my local instance.

GL on your project!

**Comment by ChemiKyle** [comment]
I unfortunately am not going to have the spare cycles to review this in the near future.

**Comment by ChemiKyle** [comment]
Hi @lsgs and @h3n0r1k, 2020 was busy indeed! I'm finally getting to this along with PHP 8 compatibility.

While reviewing this PR, I realized that the UI could use a bit of extra granularity.

I feel that splitting out `style_type` into 3 distinct fields is a better approach to granularity and prevents users from potentially needing to have common CSS copied and pasted in multiple fields:

image

This will require a major version change as well as some migration code, but I have 2.0.0 working independently of these changes. I am strongly leaning towards moving forward in this direction.

___

@lsgs are you currently deploying your fork of CSS injector from your github repository? I'd like to commit my changes to this PR but I do not want to disrupt your system.

**Comment by lsgs** [comment]
Please go ahead and deploy your upgrade @ChemiKyle! I ended up reverting to the published version of the module and use an alternative mechanism for non data entry or survey pages. It'll be great to have the facility for that in your EM.

**Comment by colinaut** [comment]
Any sense on when this PR is getting finalized? I'm working on implementing a REDCap database now and would love to make CSS changes to other pages, namely the Record Home Page and the Reports page.

Thanks for creating this module btw!

**Comment by pbchase** [comment]
@ChemiKyle are you seeing this?

**Comment by pbchase** [comment]
Addressed by PR #17

**Pull request closed without merging**
