### PR TITLE
Adding basic functionality

### PR DESCRIPTION
**Pull request by tbembersimeao**
Review steps:
- [ ] Make sure README provides a clear, complete and straight forward documentation
- [ ] Inject any random CSS and make sure it applies to your forms
- [ ] Make sure each configurable constraint works properly: "Enabled", "Apply to", and "Apply to the following forms"
- [ ] Create a second style block for a different context and make sure it works
- [ ] Make sure this feature is not vulnerable to XSS attacks (to test it, insert a script into the CSS block, e.g. `</style><script>alert('You are being attacked!');</script><style>`)

### CODE REVIEW

**Review by marlycormar — COMMENTED** [review]
Hi @tbembersimeao, the module doesn't seem to save the configuration state. For example, when adding two distinct styles, and then saving, closing, and re-opening the module configuration, the first checkbox is lost. 

**[Update]** This seems to be a REDCap bug, not related to the module. However, the 'state' is actually saved but no feedback is provided to the user. So the module is doing its job.

**Comment by marlycormar** [comment]
### Suggestions:
- Emphasize that for each style added, the user needs to enable the corresponding checkbox.
- Specify the order in which the styles are applied, i.e, *are they in order of precedence?*
- The module works for v8.4.2, maybe this version could be included.

**Comment by tbembersimeao** [comment]
@marlycormar thanks for your review! Your suggestions have been addressed, please check the last commit.

**Comment by tbembersimeao** [comment]
Merging my own PR since Marly does not have this access.

**Comment by tbembersimeao** [comment]
Merging my own PR since @marlycormar does not have this access.

**Pull request merged**
